[project]
name = "linku-data-explorer"
version = "0.1.0"
description = "Explore and extract data from Linku API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.3",
    "ruff>=0.11.2",
]
